### PR TITLE
Update RESTServer.jl

### PR DESCRIPTION
**Pull request by mdpradeep**
Support for handling POST data

### CODE REVIEW

**Comment by tanmaykm** [comment]
@mdpradeep could you please squash the commits?

**Comment by mdpradeep** [comment]
ok. but will the support for POST data not go in ?

**Comment by tanmaykm** [comment]
Of course, it will. I just wanted you to merge the 14 commits into 1.

**Comment by tanmaykm** [comment]
@mdpradeep I have squashed your commits in #17 
Will merge after testing.
I think this can now be closed.

**Comment by mdpradeep** [comment]
Thanks Tanmay.

Regards,
Pradeep

**Pull request closed without merging**
